# Generated by Django 5.1.2 on 2025-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
